### ISSUE TITLE
Bug: The player may clip through the floor near long ladders

### ISSUE THREAD

**Issue by MisterSaward** [BrandenEK/Blasphemous-Boots-of-Pleading#1]
While this mod is installed, if you hold down while standing near a ladder that reaches the floor, the Penitent One will attempt to climb down when he shouldn't be able to. While in most cases this just results in some harmless visual oddities, I came across one case where I clipped out of bounds because of it, a ladder in Jondo. I was able to cause this even without the boots equipped or in my inventory at all.

This can be quickly reproduced in Tirso's room in Albero with the long ladders that lead to the Mea Culpa shrine and Ossuary.

I stumbled across this during a randomiser run, and proceeded to uninstall mods one by one until I found the culprit, and it appears to be this one! I was using version 1.4.0 of the modding API, and version 1.0.3 of the Boots of Pleading mod.

https://github.com/BrandenEK/Blasphemous-Boots-of-Pleading/assets/137500983/bc5c847f-2233-486a-8c8d-fed7600ce3ec

**Comment by BrandenEK** [comment]
Thank you for bringing this up, and also for narrowing it down to which mod exactly was responsible for the issue!  I have put out a new release to fix the bug.

However, this does have a slight drawback where the first set of spikes in the Brotherhood spike room are unable to safely be jumped out of.  I believe this is the only area it affects though.
